### ISSUE TITLE
Missing Events 

### ISSUE THREAD

**Issue by gmolto** [grycap/cloudtrail-tracker#10]
Hi there,

There are missing RunInstances events for some users.

For example, this is the log of events gathered directly from CloudTrail (using the AWS CLI): [alucloud103-sen-log.txt](https://github.com/grycap/cloudtrail-tracker/files/2035610/alucloud103-sen-log.txt) in which 16 RunInstances events appear with different timestamps

However, issuing the following query to CloudTrailTracker:

```
curl --request GET \
  --url 'https://OBFUSCASTED.execute-api.us-east-1.amazonaws.com/dev/users/alucloud103?from=2018-02-01&to=2018-05-31'
```
only shows a single RunInstance event.

Any ideas what could be wrong?

**Comment by gmolto** [comment]
It is indeed weird.

Here are more insights:

This ([alucloud121-log-extended.txt](https://github.com/grycap/cloudtrail-tracker/files/2038574/alucloud121-log-extended.txt)
) is the extended log (now with EventId) for alucloud121 from  2018-02-01 up to now, obtained with the following query:

```
aws cloudtrail lookup-events --profile gmolto --lookup-attributes AttributeKey=Username,AttributeValue=alucloud121 --start-time 2018-02-01 | jq -r '.Events[] | "\(.EventId)  \(.EventName)  \(.EventTime)"' | awk '{printf "%s\t", $1; printf "%s\t", $2; system("date -r " $3)}'
```

And this ([alucloud121-ctt.log](https://github.com/grycap/cloudtrail-tracker/files/2038601/alucloud121-ctt.log)) is the result of the query to CloudTrailTracker:

```
https://{{CTTENDPOINT}}/users/{{USERNAME}}?from={{START_DATE}}&to={{END_DATE}}
```
where USERNAME=alucloud121, START_DATE=2018-02-02 and END_DATE = 2018-05-25

Fewer events and no correlation among them comparing the EventIds.

**Comment by gmolto** [comment]
In this example, some events appear in both logs but others do not show up:

Log obtained from AWS CLI CloudTrail:
[alucloud109-log-extended.txt](https://github.com/grycap/cloudtrail-tracker/files/2038689/alucloud109-log-extended.txt)

Log obtained from CloudTrailTracker:
[alucloud109-cloudtrail.log](https://github.com/grycap/cloudtrail-tracker/files/2038694/alucloud109-cloudtrail.log)

**Comment by JoseRPrietoF** [comment]
Fixed bug on upload events. 
Now DynamoDB Table has more than ten times events than before.
