### ISSUE TITLE
Unused parameters in settings.py 

### ISSUE THREAD

**Issue by gmolto** [grycap/cloudtrail-tracker#14]
The parameter `arn_rol` in settings.py looks like it is not used since the ARN of the role is specified in serverless.yml. Also `aws_acct_id` appears to not be used as well.

@JoseRPrietoF Could you please confirm so that I comment them out and update the documentation accordingly?

**Comment by JoseRPrietoF** [comment]
Deleted unused parameters and PR accepted.

Thanks you!
