### ISSUE TITLE
Improve Sanity Check of Input Parameters

### ISSUE THREAD

**Issue by gmolto** [grycap/cloudtrail-tracker#5]
Hi.

When issuing this query:
```
https://{{CTTENDPOINT}}/users/alucloud230?param=['instnceType','eventSource']&value=['m1.mall','ec2.amazonaws.com']&from=2017-06-06&eventName=RunInstances&to=2017-09-09
```
results are obtained even though the name of the parameter is incorrect and the name of the instance type is incorrect. The expected result is an empty list or an HTTP error such as 400 Bad Request.

**Comment by JoseRPrietoF** [comment]
We didn't pay attention to the first parameter of 'param' .
Fixed
